from django.urls import path
from . import views

urlpatterns = [
    path('api/estados/<str:estado_id>', views.get_estado_by_id),
    path('api/estados/', views.get_estados),
    path('api/estados/adicionar/<str:estados>', views.add_estados),
    path('api/cidades/<str:cidade_id>', views.get_cidade_by_id),
    path('api/cidades/', views.get_cidades),
    path('api/cidades/estado/<str:estado_id>', views.get_cidades_by_estado_id),
    path('api/cidades/adicionar/<str:estado_id>/<str:cidades>', views.add_cidades_in_estado),
    path('api/wishlist/<str:user_id>', views.get_user_wishlist),
    path('api/wishlist/', views.get_wishlist),
    path('api/wishlist/adicionar/', views.create_wishlist),
    path('api/medias/', views.get_medias),
    path('api/medias/<str:product_id>', views.get_medias_by_product_id),
    path('api/medias/picture/', views.post_media),
    path('api/medias/delete/<str:media_id>', views.delete_media),
    path('api/reviews/', views.get_reviews),
    path('api/reviews/<str:product_id>', views.get_reviews_by_product_id),
    path('api/reviews/adicionar/', views.create_review),
    path('api/notasfiscais/', views.get_notas_ficais),
    path('api/notasfiscais/<str:pedido_id>', views.get_nota_fiscal_by_pedido_id),
    path('api/notasfiscais/adicionar/', views.create_nota_fiscal),
    path('api/clientes/', views.get_clientes),
    path('api/clientes/<str:user_id>', views.get_cliente_by_id),
    path('api/clientes/email/<str:email>', views.get_cliente_by_email),
    path('api/clientes/adicionar/', views.create_cliente),
    path('api/categorias/', views.get_categorias),
    path('api/categorias/<str:categoria_id>', views.get_categoria_by_id),
    path('api/categorias/adicionar/<str:nome>', views.create_categoria),
    path('api/categorias/deletar/<str:categoria_id>', views.delete_categoria),
    path('api/pagamentos/', views.get_pagamentos),
    path('api/pagamentos/<str:pagamento_id>', views.get_pagamento_by_id),
    path('api/pagamentos/adicionar/', views.create_pagamento),
    path('api/pagamentos/deletar/<str:pagamento_id>', views.delete_pagamento),
    path('api/pedidos/', views.get_pedidos),
    path('api/pedidos/<str:pedido_id>', views.get_pedido_by_id),
    path('api/pedidos/cliente/<str:cliente_id>', views.get_pedidos_by_user_id),
    path('api/pedidos/adicionar/', views.create_pedido),
    path('api/produtos/', views.get_produtos),
    path('api/produtos/<str:produto_id>', views.get_produto_by_id),
    path('api/produtos/categoria/<str:categoria_id>', views.get_produtos_by_categoria_id),
    path('api/produtos/adicionar/', views.create_produto),
    path('api/vendedores/', views.get_vendedores),
    path('api/vendedores/<str:vendedor_id>', views.get_vendedor_by_id),
    path('api/vendedores/email/<str:email>', views.get_vendedor_by_email),
    path('api/vendedores/adicionar/', views.create_vendedor),
]