# Generated by Django 4.0.3 on 2022-04-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estados',
            new_name='Estado',
        ),
    ]
