# Generated by Django 4.0.3 on 2022-04-08 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0003_alter_estado_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cidadeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estadoId', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
