# Generated by Django 4.0.3 on 2022-04-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0004_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewId', models.CharField(max_length=200)),
                ('pedidoId', models.CharField(max_length=200)),
                ('produtoId', models.CharField(max_length=200)),
                ('reviewTitulo', models.CharField(max_length=200)),
                ('reviewComentario', models.TextField()),
                ('reviewScore', models.IntegerField()),
                ('reviewCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienteId', models.CharField(max_length=200)),
                ('produtoId', models.CharField(max_length=200)),
            ],
        ),
    ]
