# Generated by Django 4.0.3 on 2022-04-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0005_midia_review_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewCreatedAt',
            new_name='createdAt',
        ),
    ]
