# Generated by Django 4.0.3 on 2022-04-09 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0006_rename_reviewcreatedat_review_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 1, 32, 56, 287128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
