# Generated by Django 4.0.3 on 2022-04-09 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0007_remove_review_id_alter_review_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoriaNome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clienteNome', models.CharField(max_length=200)),
                ('clienteEmail', models.EmailField(max_length=254)),
                ('clienteSenha', models.CharField(max_length=200)),
                ('clienteCelular', models.CharField(max_length=200)),
                ('clienteCPF', models.CharField(max_length=20)),
                ('clienteCEP', models.CharField(max_length=15)),
                ('clienteEndereco', models.CharField(max_length=200)),
                ('clienteCidadeId', models.CharField(max_length=200)),
                ('clienteEstadoId', models.CharField(max_length=200)),
                ('clienteLatitude', models.FloatField()),
                ('clienteLongitude', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('nfeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pedidoId', models.CharField(max_length=200)),
                ('produtoId', models.CharField(max_length=200)),
                ('vendedorId', models.CharField(max_length=200)),
                ('nfeQuantidade', models.IntegerField()),
                ('nfePreco', models.FloatField()),
                ('nfeFrete', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('pagamentoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clienteId', models.CharField(max_length=200)),
                ('pedidoId', models.CharField(max_length=200)),
                ('pagamentoMetodo', models.CharField(max_length=200)),
                ('pagamentoParcelas', models.IntegerField(blank=True)),
                ('pagamentoValorTotal', models.FloatField()),
                ('pagamentoFinalCartao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedidoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produtoId', models.CharField(max_length=200)),
                ('clienteId', models.CharField(max_length=200)),
                ('vendedorId', models.CharField(max_length=200)),
                ('pedidoQuantidadeProduto', models.IntegerField()),
                ('pedidoStatus', models.BooleanField()),
                ('pedidoDataCompra', models.DateTimeField(auto_now_add=True)),
                ('pedidoDataPagamento', models.DateTimeField(blank=True)),
                ('pedidoDataTransportadora', models.DateTimeField(blank=True)),
                ('pedidoDataPrevista', models.DateTimeField()),
                ('pedidoDataEntregue', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('produtoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produtoCategoriaId', models.CharField(max_length=200)),
                ('produtoNome', models.CharField(max_length=200)),
                ('produtoDescricao', models.TextField()),
                ('produtoPreco', models.FloatField()),
                ('produtoQuantidade', models.IntegerField()),
                ('produtoAvgScore', models.FloatField()),
                ('produtoQuantidadeNotas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedorId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendedorNome', models.CharField(max_length=200)),
                ('vendedorEmail', models.EmailField(max_length=254)),
                ('vendedorSenha', models.CharField(max_length=200)),
                ('vendedorCelular', models.CharField(max_length=200)),
                ('vendedorCPF', models.CharField(max_length=20)),
                ('vendedorCEP', models.CharField(max_length=15)),
                ('vendedorEndereco', models.CharField(max_length=200)),
                ('vendedorCidadeId', models.CharField(max_length=200)),
                ('vendedorEstadoId', models.CharField(max_length=200)),
                ('vendedorLatitude', models.FloatField()),
                ('vendedorLongitude', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 2, 6, 3, 92283, tzinfo=utc)),
        ),
    ]
