# Generated by Django 4.0.3 on 2022-04-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0011_rename_productid_media_produtoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='clienteId',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
