# Generated by Django 4.0.3 on 2022-04-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0012_review_clienteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagamentoId',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
