# Generated by Django 4.0.3 on 2022-04-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0013_pedido_pagamentoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produtoVendedorId',
            field=models.CharField(default=432098340, max_length=200),
            preserve_default=False,
        ),
    ]
