# Generated by Django 4.0.3 on 2022-04-13 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0014_produto_produtovendedorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='id',
        ),
        migrations.AddField(
            model_name='media',
            name='mediaId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
