# Generated by Django 4.0.3 on 2022-04-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0015_remove_media_id_media_mediaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clienteIsVendedor',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='vendedorIsVendedor',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
