# Generated by Django 4.0.3 on 2022-04-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0016_cliente_clienteisvendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clienteIsVendedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorIsVendedor',
            field=models.BooleanField(default=True),
        ),
    ]
