# Generated by Django 4.0.3 on 2022-05-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0017_alter_cliente_clienteisvendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clienteCEP',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteCPF',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteCelular',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteCidadeId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteEndereco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteEstadoId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteIsVendedor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteLatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteLongitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteNome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteSenha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorCEP',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorCPF',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorCelular',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorCidadeId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorEndereco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorEstadoId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorIsVendedor',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorLatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorLongitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorNome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedorSenha',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
