# Generated by Django 4.0.3 on 2022-05-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0019_remove_wishlist_id_wishlist_wishlistid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedidoStatus',
            field=models.CharField(max_length=200),
        ),
    ]
