# Generated by Django 4.0.3 on 2022-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0020_alter_pedido_pedidostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedidoAvaliado',
            field=models.BooleanField(default=False),
        ),
    ]
