# Generated by Django 4.0.3 on 2022-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viasudesteapp', '0021_pedido_pedidoavaliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pagamentoId',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedidoDataEntregue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedidoDataPagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedidoDataPrevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedidoDataTransportadora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
